### ISSUE TITLE
GPS Walk (And other suggestions)

### ISSUE THREAD

**Issue by 7s26simon** [OverallLine5/MobileBandSync#12]
Great app, thanks for developing it, one issue:

1) I did a GPS run/walk and noticed that the results showed up as km but my band is set to metric and should show miles not km (the band unlocker app/dev has just fixed this issue as of today 16/02/2022 so I think it's a small bug)

Three suggestions:

1)  Is it possible that when you connect the Band 2 to the MobileBandSync app, it can set the time to sync with the time on the Windows PC? This will be extremely useful (so the Band 2 is accurate to the second)

2) Would be great if DesktopBandSync could show workout data e.g what workout you did and what heart rate was (non-GPS exercises) etc

3) If possible, for sleep tracking, it would be good if you can click a time e.g 2am, and it'll say what your heartbeat was at that specific time (not sure if that's possible, but that would be great)

Thanks

**Comment by OverallLine5** [comment]
Thanks very much!

At the top of the list are non-GPS workouts, here I'm going to show a chart without a map. Typing in the diagram already works there, I now have to implement it for the sleep diagram as well. I've missed that too :-) Especially since I store other data such as the skin temperature, which I can also display.

Funny, I already had a discussion on Discord about the Imperial system. I asked and most US users laughed and said they would prefer the metric system anyway. :-) But the idea is very good to simply take the data out of the tape, so I'll have to make sure that I read it out. I would like to synchronize the time with my smartphone or PC anyway, so I'll incorporate that.

From my point of view, these are all very good suggestions!

**Comment by OverallLine5** [comment]
> 1. I did a GPS run/walk and noticed that the results showed up as km but my band is set to metric and should show miles not km (the band unlocker app/dev has just fixed this issue as of today 16/02/2022 so I think it's a small bug)

@7s26simon Good news, I already implemented non-GPS workouts and time sync. Now I want to fix the metric stuff and I think I still don't understand that part of the issue completely.
Is the Band reset to metric upon syncing? Or is it just the app that is showing km instead of miles? Do you see miles declared as km or is it converted properly (km = miles * 1.609344)?
I can do the conversion to imperial in the app if the synchronized values are correct (but metric).

**Comment by 7s26simon** [comment]
![kilometers](https://user-images.githubusercontent.com/5106638/155992917-507f4e58-aca4-4a25-9118-4b81828eae87.png)

@OverallLine5 - thanks , will the time sync and non-GPS workouts be in the next release for desktop?

I've attached a screenshot showing what's happening. My band 2 is set to show miles, but when I import my sensor log in the app, it shows kilometers (See screenshot).

It feels like your app is defaulting to km, but it should show miles because my band 2 is set to miles. (hope that helps to describe the issue more).

Thanks

**Comment by OverallLine5** [comment]
@7s26simon Great, so it is an app issue which is already half way implemented. I just wanted to make sure that it doesn't affect your Band's settings and it's all about convering the values.
Other than suggested, I will determine the measurement units from the system running the app. And yes, I think I will update the project the next days with all of your issues and suggestions implemented. :-)

**Comment by 7s26simon** [comment]
Sounds great, thanks. I have one more idea: could you un-check the "cleanup sensor log on device" by default? I have accidentally erased a workout because I have hit "synchronize" and forgot to un-check that box.

**Comment by OverallLine5** [comment]
> It would also be very useful if we can right click and delete an activity on the homescreen of DeskopBandSync. For example, I did a sync twice and it added my sleep twice, but I cannot delete the duplicate.

Yes, good point. I will add a remove or, even better, a check for existing workouts. I always need something for the next release.
Today, I published 0.6.4 which will remember the last checkbox settings.

**Comment by 7s26simon** [comment]
Thanks, this app keeps getting better and better.

One thing I noticed about the time sync - mine seems to run 4 seconds faster than timeanddate.com - is that down to bluetooth that's making it run a few seconds fast?

And one suggestion for a future release (I don't know if this is technically possible) - but when the band 2 connects to the app (BEFORE you hit synchronize) could it sync time then? Or is it only possible to sync time when you click the button?

Thanks again for all your work on this. You're making the Band 2 very useful again!

**Comment by OverallLine5** [comment]
Thank you very much, I am glad that the Band is still being used with the app :)
A time synchronization after the connect is technically possible. Actually it's a good idea because automatic synchronization can be switch off on the Band if necessary.
As synchronization usually takes a moment to be executed, it's possible that the time is outdated. I could simply add a few seconds. :)

**Comment by 7s26simon** [comment]
Just tested it again by turning off bluetooth/closing app, then re-starting bluetooth and opening app. Each time it's running 2 seconds slow compared to Windows time. Looks like a very easy fix like you say. If you could make it "minus 2" seconds during the sync that would be cool and it would be exactly the same as the time on a Windows PC/Laptop.

And syncing after bluetooth connect would be great.

Thanks! I'll look forward to future releases. If I have any more ideas I'll post them if that's ok with you! :-)

**Comment by OverallLine5** [comment]
Sure, I benefit from the features myself! :-)

**Comment by 7s26simon** [comment]
Sorry to be a pain, I just sync’d a run and noticed that it was still showing in km in the app and miles on my watch. Pic attached. (I can’t remember if this was supposed to be fixed in this release or it’s due to be fixed.)

![Uploading 8476436C-4FAF-4645-AA13-044704D65EB8.jpeg…]()

**Comment by 7s26simon** [comment]
Just tried changing region from UK to US and re-synchronised but it didn't show as miles for me, still shows as km on my machine.

**Comment by 7s26simon** [comment]
Just done some more testing and found a possible bug?

So I changed region from UK to US, and then I did a sync. The original run changed to 'miles', but the duplicate sync stays as 'km'.

I sync'd a few more times and each time, the old sync goes to 'miles' and the new sync stays as km (hope I've explained that well! Photo attached)

![sync-walk](https://user-images.githubusercontent.com/5106638/156802595-9ea47d27-b039-4bc3-a652-eaf5a18ac299.png)

**Comment by 7s26simon** [comment]
Ignore my last post - I uninstalled and re-installed DesktopBandSync - and with region set to US, I did another sync. It now works perfectly.

Must have been something to do with the upgrade. Installing fresh works. Thanks! I'll close this and will check back for future updates/features! cheers
